### ISSUE TITLE
Audio post

### ISSUE THREAD

**Issue by richoster** [spacebetweentherapy/website#125]
work out how to embed an audio player in a journal post. Here is the code: <iframe src="https://embed.acast.com/6230990be23a6d0012c856e6/623099f4ef1f4a00130374e6?accentColor=4a4a4a&bgColor=ebebeb&secondaryColor=ae854c" frameBorder="0" width="100%" height="110px"></iframe>

**Comment by crawlem** [comment]
How's this?
![image](https://user-images.githubusercontent.com/2522254/164743773-89e3909a-4f20-4fad-bf26-87c728c0d1bb.png)

**Comment by richoster** [comment]
Looks good. 

I don’t know how much of a pain it would be to put it above the image? Just to make it more obvious. But if it is a pain, then I think this would work. The player looks great, so good job on sorting that. 



Richard Oster
Space Between Therapy
Counselling & Psychotherapy

M.  07919178308
E.   ***@***.*** 
W.  spacebetweentherapy.com   

On 22 April 2022 at 16:15:59, Mark Crawley ***@***.***) wrote:

How's this?
