### ISSUE TITLE
quote image

### ISSUE THREAD

**Issue by richoster** [spacebetweentherapy/website#34]
I wonder if a solution is to reduce the height of the image, cutting off a good chunk of the sky (either by reducing the window frame or cropping the image). Then instead of pinning the text to the bottom, pinning it to the top, just below the skyline?

**Comment by crawlem** [comment]
I removed a chunk of sky from the image, and adjusted the position of the text to be positioned from the top rather than the bottom.

**Comment by crawlem** [comment]
Review small screen behaviour next.

**Comment by crawlem** [comment]
Looks ok to me
