### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by crawlem** [spacebetweentherapy/website#39]
To me, all of the images look a little blurry, especially on the iPad. Normally this happens when you blow an image up not reduce it. It's noticeable in the headshot and the footer images. I wonder if it is something to do with the compression and I'm not sure if there is anything that can be done to fix it? But it would be great if they were a little crisper though.

**Comment by crawlem** [comment]
Ah I think I know why this is, and something I had to sort out for balloonsinc too. Will do some investigation into how we handle this with Contentful.

**Comment by crawlem** [comment]
I've found a solution for the built-in images i.e. images which are not managed in the CMS. I've improved the quality of:

- Blog post arrows
- Contact page email/phone icons
- Top left logo (on small screens)
- Home page circles logo

Still working on a solution for images managed in the CMS, which includes the headshot and footer images you mention in the ticket.

**Comment by crawlem** [comment]
We suggested removing the footer images and Rich's headshot from the CMS so we can use 2x / 3x responsive quality images for these.

**Comment by crawlem** [comment]
I've hardcoded all intro section images to be 200x200 and to expect the image in the CMS to be 400x400 (i.e. 2x). This has fixed the headshot on the homepage.

**Comment by richoster** [comment]
This is great, headshot, icons and logos look much better. The rainbow image on the home page could also be hardcoded if that's possible? I've added a filter to that image so it's more in line with the rest of the images. I've added the full version to google drive, but not added it to the site yet, as I didn't know if it needed to be a certain ratio. Can chat about that.

**Comment by richoster** [comment]
I'll need to wait until I get the logos after I qualify to play with these.

**Comment by crawlem** [comment]
Rainbow image done. Logos to follow once they're available.

**Comment by richoster** [comment]
I think this is all fixed now.
