### ISSUE TITLE
spacer dots

### ISSUE THREAD

**Issue by crawlem** [spacebetweentherapy/website#40]
On my laptop they look like dots, on the ipad they look like squares and the little icons could be a little larger to cover up the dot

**Comment by crawlem** [comment]
I've replaced the original method I used with something else.. not sure about it but at least it should look the same everywhere now...

**Comment by crawlem** [comment]
Great, this has fixed it. I like the size and spacing of the white dots. The size of the icons is now spot on as well. On some screen sizes the little white dots are a tiny bit visable on the right hand side of the icon. I wonder if a fix for this would be to shorten the white dots so they finish 5 px before the icon, in other words loose 2 white dots. I have no idea if this is possible?

**Comment by crawlem** [comment]
I've tweaked the spacing a bit - are the dots still visible to the right of the icon?

**Comment by richoster** [comment]
No, I think this has sorted it and I'm happy with how it looks.
