### ISSUE TITLE
Homepage hero image is smaller than the rest

### ISSUE THREAD

**Issue by crawlem** [spacebetweentherapy/website#47]
The [homepage hero image (of Rich & Matthew walking through Dartmoor)](https://app.contentful.com/spaces/eia1ph7h56y6/assets/45ZVG4G6ZDW2P7B9apB7vi) is a smaller resolution than the other hero images.

Is there a higher resolution version available so we could re-cut it to 2048 x 1536 to match the others?

**Comment by richoster** [comment]
I think that is the best res I have. Could I recut the others to match the home page or do you think the quality will be too poor?

**Comment by richoster** [comment]
Looking at I think I might have a high res image, but the issue is that I only need a small section of the photo and I want Matthew and I to be in the right position and to have the right balance of sky/grass

**Comment by crawlem** [comment]
It's not a major issue. The other pages are using higher res images so we should probably leave them as they are. The homepage can keep using the image we have for now, but if you do find a higher res one it would help up the quality a little bit.
