### ISSUE TITLE
Higher resolution circles logo image

### ISSUE THREAD

**Issue by crawlem** [spacebetweentherapy/website#48]
The circles.png file in Google Drive is 420 pixels wide. Could you re-cut one at higher resolution say 500 px wide?

I've started improving the resolution of images for high DPI screens (e.g. iPhone, iPad), but need a bigger version of this one.

**Comment by richoster** [comment]
I've done that and uploaded it to the google drive. Let me know if I've not done it correctly.

**Comment by crawlem** [comment]
Fab thanks, I've added that in.
